#!/usr/bin/env bash

clear

echo "You are about to set up your Ruby on Rails development environment just right."
echo -n "Press [ENTER] to begin ..."
read USER_COMFIRM

echo "Checking for SSH key ..."
if [[ -f ~/.ssh/id_rsa.pub ]]; then
  echo -n 'Default SSH key already exists. '
fi
echo -n 'Do you want to create a new SSH key? (y/n) '
read USER_COMFIRM
[ "$USER_COMFIRM" = "y" ] && ssh-keygen -t rsa

#echo "Copying public key to clipboard. Paste it into your Github account ..."
#  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | xclip
#  open https://github.com/account/ssh

echo "Using apt-get to install OS packages so let's update it first ..."
  sudo apt-get update -y

echo "Installing OS packages. You will be prompted for your password ..."
  sudo apt-get install build-essential openssl ri ruby ruby1.8 ruby-dev rake libruby1.8 git-gui gitk libxslt1-dev libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison curl -y

echo "Installing MySQL 5.1. You will need to enter a root password ..."
  sudo apt-get install mysql-client-5.1 mysql-server-5.1 libmysqlclient-dev libmysql-ruby mysql-admin

echo "Installing mongoDB-2.0.1 ..."
  # see this: http://crazygui.wordpress.com/2011/10/31/installing-mongodb-2-0-on-ubuntu-11-10/

echo "Installing ack, a good way to search through files ..."
  sudo apt-get install ack-grep -y

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  sudo apt-get install imagemagick --fix-missing -y

echo "Installing RVM (Ruby Version Manager) ..."
  curl -s https://rvm.beginrescueend.com/install/rvm -o rvm-installer ; chmod +x rvm-installer ; ./rvm-installer --version latest
  rm rvm-installer

echo "Installing Ruby 1.8.7 stable ..."
  rvm install 1.8.7
  rvm use 1.8.7

echo "Installing Ruby 1.9.2 stable and making it the default Ruby ..."
  rvm install 1.9.2-p290
  rvm use 1.9.2 --default

echo "Installing Rails to write and run web applications ..."
  gem install rails --no-rdoc --no-ri

echo "Installing the database gems ..."
  gem install mysql2 sqlite3 capistrano capistrano-ext hirb wirble --no-rdoc --no-ri

echo "Installing the deployment gems ..."
  gem install capistrano capistrano-ext --no-rdoc --no-ri

echo "Installing the console gems ..."
  gem install hirb wirble --no-rdoc --no-ri

echo "Installing the testing gems ..."
  gem install capybara capybara-webkit cucumber-rails factory_girl_rails launchy mocha ruby_parser shoulda rspec-rails --no-rdoc --no-ri

echo " +---------------------------------------------------------------+ "
echo " | Your Ruby on Rails development environment is now just right! |"
echo " +---------------------------------------------------------------+ "

# Exit cleanly.
exit 0