#!/usr/bin/env bash

echo "You are about to set up your Ruby on Rails development environment just right."
echo -n "Press [ENTER] to begin ..."
read USER_COMFIRM

clear

bash < <(curl -s https://raw.github.com/edjames/just_right/master/ssh)

bash < <(curl -s https://raw.github.com/edjames/just_right/master/apt-update)

echo "Installing OS packages ... "
  sudo apt-get install build-essential openssl ri ruby ruby1.8 ruby-dev rake libruby1.8 git-gui gitk libxslt1-dev libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison curl -y

echo "Installing MySQL 5.1. You will need to enter a root password ..."
  sudo apt-get install mysql-client-5.1 mysql-server-5.1 libmysqlclient-dev libmysql-ruby mysql-admin

echo -n "Do you want to install MongoDB? (y/n) "
read USER_CONFIRM
[ "$USER_CONFIRM" = "y" ] && bash < <(curl -s https://raw.github.com/edjames/just_right/master/ubuntu_user)

echo "Installing ack, a good way to search through files ..."
  sudo apt-get install ack-grep -y

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  sudo apt-get install imagemagick --fix-missing -y

echo "Installing RVM (Ruby Version Manager) ..."
  curl -s https://rvm.beginrescueend.com/install/rvm -o rvm-installer ; chmod +x rvm-installer ; ./rvm-installer --version latest
  rm rvm-installer

echo "Installing Ruby 1.8.7 stable ..."
  rvm install 1.8.7
  rvm use 1.8.7

echo "Installing Ruby 1.9.2 stable and making it the default Ruby ..."
  rvm install 1.9.2-p290
  rvm use 1.9.2 --default

echo "Installing Rails to write and run web applications ..."
  gem install rails --no-rdoc --no-ri

echo "Installing the database gems ..."
  gem install mysql2 sqlite3 capistrano capistrano-ext hirb wirble --no-rdoc --no-ri

echo "Installing the deployment gems ..."
  gem install capistrano capistrano-ext --no-rdoc --no-ri

echo "Installing the console gems ..."
  gem install hirb wirble --no-rdoc --no-ri

echo "Installing the testing gems ..."
  gem install capybara capybara-webkit cucumber-rails factory_girl_rails launchy mocha ruby_parser shoulda rspec-rails --no-rdoc --no-ri

echo " +---------------------------------------------------------------+ "
echo " | Your Ruby on Rails development environment is now just right! |"
echo " +---------------------------------------------------------------+ "

# Exit cleanly.
exit 0