#!/usr/bin/env bash

echo "You are about to set up your Ruby on Rails development environment just right."
echo -n "Press [ENTER] to begin ..."
read USER_COMFIRM

clear

bash -c "$(curl -s https://raw.github.com/edjames/just_right/master/apt-update)"

echo "Installing OS packages ... "
  sudo apt-get install build-essential openssl ri ruby ruby1.8 ruby-dev rake libruby1.8 git-gui gitk libxslt1-dev libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison xclip -y -qq

bash -c "$(curl -s https://raw.github.com/edjames/just_right/master/ruby)"

bash -c "$(curl -s https://raw.github.com/edjames/just_right/master/ssh)"

echo "Installing MySQL 5.1. You will need to enter a root password ..."
  sudo apt-get install mysql-client-5.1 mysql-server-5.1 libmysqlclient-dev libmysql-ruby mysql-admin -y -qq

echo -n "Do you want to install MongoDB? (y/n) "
read USER_CONFIRM
[ "$USER_CONFIRM" = "y" ] && bash -c "$(curl -s https://raw.github.com/edjames/just_right/master/mongodb)"

echo "Installing ack, a good way to search through files ..."
  sudo apt-get install ack-grep -y

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  sudo apt-get install imagemagick --fix-missing -y

echo " +---------------------------------------------------------------+ "
echo " | Your Ruby on Rails development environment is now just right! | "
echo " +---------------------------------------------------------------+ "

# Exit cleanly.
exit 0