#!/usr/bin/env bash

# 
# This file is NOT included in the Just Right project.
# It is only to be used for testing and proving that
# commands and routines actually run successfully.
# 
function _execute_asset {
  echo "curl -s https://raw.github.com/edjames/just_right/develop/$1/$2" ;
}

function _ubuntu_user_asset {
  _execute_asset "ubuntu_user_assets" $1 ;
}

function _shared_asset {
  _execute_asset "shared_assets" $1 ;
}

clear

echo ; echo "You are about to set up your Ubuntu machine just right." ; echo

_shared_asset "distro_warning" ;
_ubuntu_user_asset "enter_to_begin" ;

exit

echo -n "Press [ENTER] to begin ..."
read USER_COMFIRM
[ "$USER_COMFIRM" = "y" ] && eval "$(cat sandbox2)"


echo " +--------------------------------------------+ "
echo " | Your development environment is now ready! |"
echo " +--------------------------------------------+ "

# Exit cleanly.
exit 0

# echo Please, enter your name
# read NAME
# echo "Hi $NAME!"