#!/usr/bin/env bash

# 
# This file is NOT included in the Just Right project.
# It is only to be used for testing and proving that
# commands and routines actually run successfully.
# 

clear

function _do_install {
  local package ;
  for package ; do
    echo "sudo apt-get install ${package}" ;
  done
}

_do_install "package1" ;
_do_install "package2" ;

echo -n "Press [ENTER] to begin ..."
read USER_COMFIRM
[ "$USER_COMFIRM" = "y" ] && eval "$(cat sandbox2)"


echo " +--------------------------------------------+ "
echo " | Your development environment is now ready! |"
echo " +--------------------------------------------+ "

# Exit cleanly.
exit 0

# echo Please, enter your name
# read NAME
# echo "Hi $NAME!"