#!/usr/bin/env bash

echo "Checking for SSH key ..."
if [[ -f ~/.ssh/id_rsa.pub ]]; then
  echo -n 'Default SSH key already exists. '
fi
echo -n 'Do you want to create a new SSH key? (y/n) '
read USER_COMFIRM
[ "$USER_COMFIRM" = "y" ] && ssh-keygen -t rsa

#echo "Copying public key to clipboard. Paste it into your Github account ..."
#  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | xclip
#  open https://github.com/account/ssh