#!/usr/bin/env bash

# Temporary utility functions
function _execute_asset {
  eval "$(curl -s https://raw.github.com/edjames/just_right/master/$1/$2)" ;
}

function _shared_asset {
  _execute_asset "shared_assets" $1 ;
}

function _ubuntu_user_asset {
  _execute_asset "ubuntu_user_assets" $1 ;
}

clear

echo ; echo "You are about to set up your Ubuntu machine just right." ; echo

_shared_asset "distro_warning" ;
_shared_asset "enter_to_begin" ;

clear

echo "Retrieving new lists of packages ..."
  sudo apt-get update -qq

_ubuntu_user_asset "medibuntu"
_ubuntu_user_asset "restricted_extras"
_ubuntu_user_asset "dconf-tools"
_ubuntu_user_asset "ubuntu-tweak"
_ubuntu_user_asset "compiz"
_ubuntu_user_asset "synaptic"
_ubuntu_user_asset "terminator"
_ubuntu_user_asset "gnome-tweak"
_ubuntu_user_asset "vlc"
_ubuntu_user_asset "jupiter"
_ubuntu_user_asset "caffeine"
_ubuntu_user_asset "sushi"
_ubuntu_user_asset "light-dm"
_ubuntu_user_asset "sysmonitor"
_ubuntu_user_asset "dropbox"
_ubuntu_user_asset "skype"
_ubuntu_user_asset "open-jdk"
_ubuntu_user_asset "unity_tweaks"

cat << MSG

  +---------------------------------------------------------+
  | Congratulations! Your Ubuntu machine is now just right! |
  +---------------------------------------------------------+

MSG

# Clean up temporary utility functions
unset _execute_asset ;
unset _shared_asset ;
unset _ubuntu_user_asset ;

# Exit cleanly.
exit 0