#!/usr/bin/env bash

echo "You are about to set your Ubuntu machine just right."
echo -n "Press [ENTER] to begin ..."
read USER_COMFIRM

clear

bash -c "$(curl -s https://raw.github.com/edjames/just_right/develop/apt-update)"

echo "Installing Ubuntu Restricted Extras and enabling full DVD playback ..."
  sudo apt-get install ubuntu-restricted-extras libdvdread4 -y -qq
  sudo /usr/share/doc/libdvdread4/install-css.sh

echo "Installing Compiz Config Settings Manager ..."
  sudo apt-get install compizconfig-settings-manager -y -qq

echo "Installing Synaptic ..."
  sudo apt-get install synaptic -y -qq

echo "Installing Terminator ..."
  sudo apt-get install terminator -y -qq

echo "Installing GNOME Tweak Tool ..."
  sudo apt-get install gnome-tweak-tool -y -qq

echo "Installing VLC ..."
  sudo apt-get install vlc -y -qq

echo "Installing Jupiter for better power management ..."
  sudo add-apt-repository ppa:webupd8team/jupiter -y
  sudo apt-get update -qq
  sudo apt-get install jupiter -y -qq

echo "Installing Caffeine to stop screensaver interruptions ..."
  sudo add-apt-repository ppa:caffeine-developers/ppa -y
  sudo apt-get update -qq
  sudo apt-get install caffeine python-glade2 -y -qq

echo "Installing web apps and Sushi file previewer ..."
  sudo add-apt-repository ppa:webupd8team/gnome3 -y
  sudo apt-get update -qq
  sudo apt-get install epiphany-browser gnome-sushi -y -qq

echo "Installing Simple LightDM Manager ..."
  sudo add-apt-repository ppa:claudiocn/slm -y
  sudo apt-get update -qq
  sudo apt-get install simple-lightdm-manager -y -qq

echo "Installing Sysmonitor App Indicator ..."
  sudo add-apt-repository ppa:alexeftimie/ppa -y
  sudo apt-get update -qq
  sudo apt-get install indicator-sysmonitor -y -qq

echo -n "Installing OpenJDK (Java 7) ..."
  sudo apt-get install openjdk-7-jre -y -qq

echo "Opening additional application pages in default browser ..."
  xdg-open http://www.skype.com/intl/en/get-skype/on-your-computer/linux/
  xdg-open https://www.virtualbox.org/wiki/Linux_Downloads
  xdg-open http://www.jetbrains.com/ruby/

echo " +----------------------------------------+ "
echo " | Your Ubuntu machine is now just right! |"
echo " +----------------------------------------+ "

# Exit cleanly.
exit 0