#!/usr/bin/env bash

echo "You are about to set your Ubuntu machine just right."
echo -n "Press [ENTER] to begin ..."
read USER_COMFIRM

clear

bash < <(curl -s https://raw.github.com/edjames/just_right/develop/apt-update)

echo "Installing Ubuntu Restricted Extras and enabling full DVD playback ..."
  sudo apt-get install ubuntu-restricted-extras
  sudo wget http://www.medibuntu.org/sources.list.d/oneiric.list -O /etc/apt/sources.list.d/medibuntu.list
  sudo apt-get --quiet update && sudo apt-get install medibuntu-keyring && sudo apt-get --quiet update
  sudo apt-get install libdvdcss2

echo "Installing Compiz Config Settings Manager ..."
  sudo apt-get install compizconfig-settings-manager

echo "Installing Synaptic ..."
  sudo apt-get install synaptic

echo "Installing Terminator ..."
  sudo apt-get install terminator

echo "Installing GNOME Tweak Tool ..."
  sudo apt-get install gnome-tweak-tool

echo "Installing VLC ..."
  sudo apt-get install vlc

echo "Installing Jupiter for better power management ..."
  sudo add-apt-repository ppa:webupd8team/jupiter
  sudo apt-get update
  sudo apt-get install jupiter

echo "Installing Caffeine to stop screensaver interruptions ..."
  sudo add-apt-repository ppa:caffeine-developers/ppa
  sudo apt-get update
  sudo apt-get install caffeine python-glade2

echo "Installing web apps and Sushi file previewer ..."
  sudo add-apt-repository ppa:webupd8team/gnome3
  sudo apt-get update
  sudo apt-get install epiphany-browser
  sudo apt-get install gnome-sushi

echo "Installing Simple LightDM Manager ..."
  sudo apt-add-repository ppa:claudiocn/slm
  sudo apt-get update
  sudo apt-get install simple-lightdm-manager

echo "Installing Sysmonitor App Indicator ..."
  sudo add-apt-repository ppa:alexeftimie/ppa
  sudo apt-get update --quiet
  sudo apt-get install indicator-sysmonitor

echo -n "Do you want to install OpenJDK (Java 7)? (y/n) "
read USER_COMFIRM
[ "$USER_COMFIRM" = "y" ] && sudo apt-get install openjdk-7-jre

echo "Opening additinoal application in default browser ..."
  xdg-open http://www.skype.com/intl/en/get-skype/on-your-computer/linux/
  xdg-open https://www.virtualbox.org/wiki/Linux_Downloads
  xdg-open http://www.jetbrains.com/ruby/

echo " +----------------------------------------+ "
echo " | Your Ubuntu machine is now just right! |"
echo " +----------------------------------------+ "

# Exit cleanly.
exit 0