#!/usr/bin/env bash

echo ; echo "Installing Caffeine to stop screensaver interruptions ..." ; echo
  sudo add-apt-repository ppa:caffeine-developers/ppa -y
  sudo apt-get update -qq
  sudo apt-get install caffeine python-glade2 -y -qq