#!/usr/bin/env bash

echo ; echo "Installing Simple LightDM Manager ..." ; echo
  sudo add-apt-repository ppa:claudiocn/slm -y
  sudo apt-get update -qq
  sudo apt-get install simple-lightdm-manager -y -qq