#!/usr/bin/env bash

echo " ** Asset ** "
echo "Installing Simple LightDM Manager ..."
  sudo add-apt-repository ppa:claudiocn/slm -y
  sudo apt-get update -qq
  sudo apt-get install simple-lightdm-manager -y -qq