#!/usr/bin/env bash

echo " ** Asset ** "
echo "Adding medibuntu repositories ..."
  sudo wget --output-document=/etc/apt/sources.list.d/medibuntu.list http://www.medibuntu.org/sources.list.d/$(lsb_release -cs).list
  sudo apt-get update -qq
  sudo apt-get install medibuntu-keyring -y -qq --allow-unauthenticated
  sudo apt-get update -qq
  sudo apt-get install app-install-data-medibuntu apport-hooks-medibuntu -y -qq