#!/usr/bin/env bash

echo " ** Asset ** "
echo "Installing Ubuntu Restricted Extras and enabling full DVD playback ..."
  sudo apt-get install ubuntu-restricted-extras libdvdread4 -y -qq
  sudo /usr/share/doc/libdvdread4/install-css.sh
