#!/usr/bin/env bash

echo ; echo "Installing web apps and Sushi file previewer ..." ; echo
  sudo add-apt-repository ppa:webupd8team/gnome3 -y
  sudo apt-get update -qq
  sudo apt-get install epiphany-browser gnome-sushi -y -qq