#!/usr/bin/env bash

echo ; echo "Installing Sysmonitor App Indicator ..." ; echo
  sudo add-apt-repository ppa:alexeftimie/ppa -y
  sudo apt-get update -qq
  sudo apt-get install indicator-sysmonitor -y -qq