#!/usr/bin/env bash

echo "Installing Rails to write and run web applications ..."
  gem install rails --no-rdoc --no-ri

echo "Installing the database gems ..."
  gem install mysql2 sqlite3 capistrano capistrano-ext hirb wirble --no-rdoc --no-ri

echo "Installing the deployment gems ..."
  gem install capistrano capistrano-ext --no-rdoc --no-ri

echo "Installing the console gems ..."
  gem install hirb wirble --no-rdoc --no-ri

echo "Installing the testing gems ..."
  gem install capybara capybara-webkit cucumber-rails factory_girl_rails launchy mocha ruby_parser shoulda rspec-rails --no-rdoc --no-ri
