#!/usr/bin/env bash

echo ; echo "Installing RVM (Ruby Version Manager) ..." ; echo
  curl -s https://rvm.beginrescueend.com/install/rvm -o rvm-installer ; chmod +x rvm-installer ; ./rvm-installer --version latest
  rm rvm-installer
  source "${HOME}/.rvm/scripts/rvm"

echo "Installing Ruby 1.8.7 stable ..."
  rvm install 1.8.7
  rvm use 1.8.7

echo "Installing Ruby 1.9.2 stable and making it the default Ruby ..."
  rvm install 1.9.2-p290
  rvm use 1.9.2@global --default
